services:
  # The main DeFi State Engine application.
  defistate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: defistate
    restart: unless-stopped
    ports:
      # The host port (left side) is flexible via the .env file.
      # The container port (right side) is fixed at 8080.
      - "${DEFISTATE_JSON_RPC_PORT:-8080}:8080"
      - "127.0.0.1:${DEFISTATE_METRICS_PORT:-2112}:2112"
      - "127.0.0.1:${DEFISTATE_PPROF_PORT:-6060}:6060"
    volumes:
      - ./config.yaml:/app/config.yaml