package server

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"math/big"
	"net/http"
	"sync"
	"testing"
	"time"

	"github.com/defistate/defistate/differ"
	"github.com/defistate/defistate/engine"
	"github.com/ethereum/go-ethereum/rpc"
	"github.com/stretchr/testify/require"
)

// --------------------------------------------------------------------------------
// --- Mocks ---
// --------------------------------------------------------------------------------

// mockStateEngine implements StateEngine
type mockStateEngine struct {
	mu           sync.Mutex
	sub          *engine.Subscription
	unsubscribed bool
}

func newMockStateEngine(c <-chan *engine.State, done <-chan struct{}) *mockStateEngine {
	return &mockStateEngine{
		sub: engine.NewSubscription(c, done),
	}
}

func (m *mockStateEngine) Subscribe() (*engine.Subscription, func()) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.unsubscribed = false
	unsubscribe := func() {
		m.mu.Lock()
		defer m.mu.Unlock()
		m.unsubscribed = true
	}
	return m.sub, unsubscribe
}

func (m *mockStateEngine) isUnsubscribed() bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.unsubscribed
}

// mockStateDiffer implements StateDiffer
type mockStateDiffer struct{}

// Diff correctly returns (diff, error) to match the interface
func (m *mockStateDiffer) Diff(prev, new *engine.State) (*differ.StateDiff, error) {
	diff := &differ.StateDiff{}
	if prev != nil {
		diff.FromBlock = prev.Block.Number.Uint64()
	}
	if new != nil {
		diff.ToBlock = new.Block
	}
	return diff, nil
}

// MockStateStreamer simulates the RPC server behavior for Client tests
type MockStateStreamer struct {
	events chan *SubscriptionEvent
	t      *testing.T
}

// Subscribe matches the standard "defi_subscribe" call generated by the client
func (streamer *MockStateStreamer) StateStream(ctx context.Context) (*rpc.Subscription, error) {
	notifier, supported := rpc.NotifierFromContext(ctx)
	if !supported {
		return nil, rpc.ErrNotificationsUnsupported
	}

	rpcSub := notifier.CreateSubscription()
	go func() {
		for event := range streamer.events {
			select {
			case <-rpcSub.Err():
				return
			default:
				if err := notifier.Notify(rpcSub.ID, event); err != nil {
					streamer.t.Logf("Error notifying subscriber: %v", err)
					return
				}
			}
		}
	}()
	return rpcSub, nil
}

func SetupMockStateStreamer(ctx context.Context, t *testing.T, port int, events []*SubscriptionEvent) (<-chan error, error) {
	eventChan := make(chan *SubscriptionEvent, len(events))
	for _, e := range events {
		eventChan <- e
	}
	close(eventChan)

	streamer := &MockStateStreamer{events: eventChan, t: t}
	server := rpc.NewServer()
	if err := server.RegisterName("defi", streamer); err != nil {
		return nil, fmt.Errorf("failed to register API: %v", err)
	}

	wsHandler := server.WebsocketHandler([]string{"*"})
	httpServer := &http.Server{Addr: fmt.Sprintf(":%d", port), Handler: wsHandler}

	errChan := make(chan error, 1)
	go func() {
		if err := httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			errChan <- err
		}
	}()
	go func() {
		<-ctx.Done()
		server.Stop()
		_ = httpServer.Shutdown(context.Background())
	}()

	return errChan, nil
}

// --------------------------------------------------------------------------------
// --- Tests ---
// --------------------------------------------------------------------------------

// TestStateStreamerServer tests the Server Logic (StateStreamer)
func TestStateStreamerServer(t *testing.T) {
	t.Run("should send full state, then diffs, then full state again", func(t *testing.T) {
		stateCh := make(chan *engine.State, 5)
		mockStateEngine := newMockStateEngine(stateCh, make(chan struct{}))
		differ := &mockStateDiffer{}

		// Use a no-op logger for tests
		logger := slog.New(slog.NewTextHandler(io.Discard, nil))

		streamer, err := NewStateStreamer(&Config{
			Engine:            mockStateEngine,
			Differ:            differ,
			Logger:            logger,
			FullStateInterval: 3,
		})
		require.NoError(t, err)

		ctx, cancel := context.WithCancel(context.Background())
		defer cancel()
		_, err = StartStreamer(ctx, streamer, 18889, []string{""})
		require.NoError(t, err)

		client, err := rpc.DialContext(ctx, "ws://localhost:18889")
		require.NoError(t, err)
		defer client.Close()

		ch := make(chan *SubscriptionEvent)
		sub, err := client.Subscribe(ctx, RpcNamespace, ch, StateStreamSubscriptionMethod)
		require.NoError(t, err)

		readEvent := func() *SubscriptionEvent {
			select {
			case event := <-ch:
				return event
			case <-time.After(5 * time.Second): // Increased Timeout
				t.Fatal("Timeout waiting for event")
				return nil
			}
		}

		// 1. Full State (First)
		stateCh <- &engine.State{Block: engine.BlockSummary{Number: big.NewInt(100)}}
		require.Equal(t, EventTypeFull, readEvent().Type)

		// 2. Diff
		stateCh <- &engine.State{Block: engine.BlockSummary{Number: big.NewInt(101)}}
		require.Equal(t, EventTypeDiff, readEvent().Type)

		// 3. Diff
		stateCh <- &engine.State{Block: engine.BlockSummary{Number: big.NewInt(102)}}
		require.Equal(t, EventTypeDiff, readEvent().Type)

		// 4. Full State (Interval)
		stateCh <- &engine.State{Block: engine.BlockSummary{Number: big.NewInt(103)}}
		require.Equal(t, EventTypeFull, readEvent().Type)

		sub.Unsubscribe()
		require.Eventually(t, mockStateEngine.isUnsubscribed, 2*time.Second, 50*time.Millisecond)
	})

	t.Run("should force full state after an error to self-heal", func(t *testing.T) {
		stateCh := make(chan *engine.State, 5)
		mockStateEngine := newMockStateEngine(stateCh, make(chan struct{}))
		differ := &mockStateDiffer{}
		logger := slog.New(slog.NewTextHandler(io.Discard, nil))

		streamer, err := NewStateStreamer(&Config{
			Engine:            mockStateEngine,
			Differ:            differ,
			Logger:            logger,
			FullStateInterval: 4,
		})
		require.NoError(t, err)

		ctx, cancel := context.WithCancel(context.Background())
		defer cancel()
		_, err = StartStreamer(ctx, streamer, 18891, []string{""})
		require.NoError(t, err)

		client, err := rpc.DialContext(ctx, "ws://localhost:18891")
		require.NoError(t, err)
		defer client.Close()

		ch := make(chan *SubscriptionEvent)
		sub, err := client.Subscribe(ctx, RpcNamespace, ch, StateStreamSubscriptionMethod)
		require.NoError(t, err)

		readEvent := func() *SubscriptionEvent {
			select {
			case event := <-ch:
				return event
			case <-sub.Err():
				return nil
			case <-time.After(5 * time.Second): // Increased Timeout
				t.Fatal("Timeout waiting for event")
				return nil
			}
		}

		// 1. Full
		stateCh <- &engine.State{Block: engine.BlockSummary{Number: big.NewInt(100)}}
		require.Equal(t, EventTypeFull, readEvent().Type)

		// 2. Error -> Full
		stateWithError := &engine.State{
			Block: engine.BlockSummary{Number: big.NewInt(101)},
			Protocols: map[engine.ProtocolID]engine.ProtocolState{
				"uniswap_v2": {Error: "failed"},
			},
		}
		stateCh <- stateWithError
		require.Equal(t, EventTypeFull, readEvent().Type)

		// 3. Next Healthy -> Full (Self-Heal)
		stateCh <- &engine.State{Block: engine.BlockSummary{Number: big.NewInt(102)}}
		require.Equal(t, EventTypeFull, readEvent().Type)

		// 4. Next Healthy -> Diff (Back to normal)
		stateCh <- &engine.State{Block: engine.BlockSummary{Number: big.NewInt(103)}}
		require.Equal(t, EventTypeDiff, readEvent().Type)
	})
}
